### ISSUE TITLE
Project Defunct -> See new Project

### ISSUE THREAD

**Issue by bramski** [c-trimm/moment-recur#18]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

@c-trimm If you want to continue working and updating this project please let me know!  I'm taking ownership because I need this plugin to work and move forward with moment.

**Comment by c-trimm** [comment]
Hello bramski,

I did plan to continue working on this, but recently began a new job and haven't had a whole lot of time/energy to do so. I have another project I'm working on that's going to require this very soon, so I was planning on making updates to it at that time.

Can you please issue pull requests to this project instead of creating another version of it? I'll be sure to pull them in and update everything this weekend.

**Comment by c-trimm** [comment]
I've added you as a collaborator on the project, as well. Since this repo is linked from the momentjs website, it would be best if it just stayed here. I really wish you would have just asked instead of cloning the project completely. I would have been happy for the help.

**Comment by bramski** [comment]
Awesome!  I've merged the other project into this one and deleted my repo.

Apologies for my neanderthal style approach; but I knew it would be easy to rectify had you responded, which you have!  I have done very little feature wise other than improve the structure of the project at this time.  Thanks!

Most of my changes are finished except that I would like to see continuous integration added to the project.  CircleCI offers open source projects integration for free.  However only an administrator of a project may sign up, so I'll open up an issue and you may get to it at your leisure.  Since i've added karma testing through gulp the project is now conveniently testable for automated tools and command line.
