### ISSUE TITLE
ranges: daysOfWeek: Change a Calendar-Based Rule?

### ISSUE THREAD

**Issue by poing** [c-trimm/moment-recur#67]
I am trying to change daysOfWeek rules.  The source data I am working with uses 1-7.  
But it's unclear how I can make this change.  This is what I have so far, but the documentation is lacking details.  
```javascript
moment().recur({
    rules: [
        { units: { low: 1, high: 7 }, measure: "daysOfWeek" }
    ]
});
```

**Comment by CorasApps** [comment]
I'm trying to understand the intended result of the rule in your code.  

Rules inside a moment().recur function, as you have above, are applied when recurring dates are generated. It is an alternate syntax to the .every() style. [See jsFiddle.](http://jsfiddle.net/rLjQx/661/)

**Comment by poing** [comment]
I am trying to change the daysOfWeek rule, adapting it to my dataset.  
The source data uses  Sunday = 1.

Check out [this jsFiddle](http://jsfiddle.net/poing/8c2m5w5j/) for a better idea of what I am trying to do.

**Comment by CorasApps** [comment]
@poing: Thanks for the additional details.

I don't see a way to customize moment-recur in this way. (I am not the ultimate authority, but that's what I have determined.)

However, you may be able to get what you need by a customization of the underlying moment functionality. The default is for weekdays to start with Sunday. The code below will change this so that the weekdays start on Saturday.

moment.updateLocale('en', {
    weekdays : [
        "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" 
    ]
});

[Another fiddle](http://jsfiddle.net/8c2m5w5j/17/)

**Comment by poing** [comment]
@CorasApps thanks for the work-around.  The jsFiddle was just a rough prototype, to give an idea of what I was looking for.  Since the work-around is just a cosmetic fix, it doesn't work for my actual needs.  It doesn't actually affect the underlying dates. 

After digging through the code, it **appears** possible to set `Calendar.ranges()` with a rule.  But `createCalendarRule()` **implicitly** prevents a new setting.  The new range **must** match the hard-coded value.  It's even verified against `moment()` to insure validity.  

Looks like my **only** option is to iterate through the values to normalize my data with daysOfWeek.  -or-  _Try to get the software vendor to represent daysOfWeek correctly._

**Thank You**
